#!/bin/sh
ARGOPW=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo)

yes | argocd login localhost:30080 --username admin --password "$ARGOPW" --insecure